name: Compile

on:
  push:
    branches: [master]
    paths:
      - "**.sp"
      - "**.inc"
    tags:
      - v*
  pull_request:
    branches: [master]
    paths:
      - "**.sp"
      - "**.inc"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: SourceMod
        run: |
          wget -q "http://www.sourcemod.net/latest.php?version=1.10&os=linux" -O sourcemod.tar.gz
          tar -xf sourcemod.tar.gz
      - name: Compile
        working-directory: ./addons/sourcemod/scripting
        run: |
          ./spcomp navmesh.sp -o navmesh.smx
      - name: Compile Test Plugin
        working-directory: ./addons/sourcemod/scripting
        run: |
          ./spcomp navmesh-test.sp -o navmesh-test.smx
      - name: Release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./addons/sourcemod/scripting/include/navmesh.inc
            ./addons/sourcemod/scripting/navmesh.smx
            ./addons/sourcemod/scripting/navmesh-test.smx
